### ISSUE TITLE
Create unit tests for argo status updater module

### ISSUE THREAD

**Issue by bozerkins** [shini4i/argo-watcher#130]
There's a module that recurrently checks if Argo CD images has been deployed, located in a file `argo_status_updater.go` 

Create unit tests that cover the functionality of that module. After the unit tests are in place, we can refactor the module to be less convoluted.

We can start this after #122 is merged

**Comment by shini4i** [comment]
@bozerkins, this was resolved by #168, correct??

**Comment by bozerkins** [comment]
Yes. Also, I think #168 reduced the size of the Argo updater more than twice.
