### ISSUE TITLE
disabling refresh makes argo do HTTP requests for tasks every second

### ISSUE THREAD

**Issue by bozerkins** [shini4i/argo-watcher#263]
If you set Auto-Refresh to Off, ArgoWatcher frontend starts doing AJAX requests every second, eventually hanging the page.

**Comment by shini4i** [comment]
@bozerkins, can you provide a way to reproduce it? I don't see this behavior locally or in any of the existing environments.

**Comment by shini4i** [comment]
Closing as non-reproduceable.
